### ISSUE TITLE
qual é a licença deste repositório?

### ISSUE THREAD

**Issue by ghost** [alissonandrade2020/gofinances#21]
Oi.

Gostaria de saber qual é a licença deste repositório. Qual é a licença deste repositório? é o MIT? GPL? Unlicensed? (Gostaria de usar o repositório para algo que estou fazendo, criando)

**Comment by alissonandrade2020** [comment]
Bom dia!

Acredito que você pode usar, sem problemas...só não esquece de dar um crédito, rsrs
